name: Create Release

# This workflow triggers, if a new tag is pushed that matches the format of
# a release version.
on:
  push:
    tags:
      - 'v*.*.*' # Push events to matching semver tags, i.e. v1.0.0, v20.15.10

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          #draft: true
          prerelease: false